@startuml UC-diagram
title Use Case Diagram - LaporKota
left to right direction

actor "Warga" as warga
actor "Tim Administrasi" as admin
actor "Eksekutor Lapangan" as eksekutor

rectangle "Sistem LaporKota" {
  usecase "Mengirim Laporan Kerusakan" as UC1
  usecase "Memvalidasi Laporan Baru" as UC2
  usecase "Melihat Penugasan Lapangan" as UC3
  usecase "Melaporkan Hasil Perbaikan" as UC4
  usecase "Mengevaluasi Hasil Kerja" as UC5
  usecase "Memantau Status Laporan" as UC6
  usecase "Mengupdate Status Laporan" as UC_Status
  usecase "Meminta Perbaikan Ulang" as UC_Rework
  usecase "Melakukan Upvote Laporan" as UC_Upvote
}

warga -- UC1
admin -- UC2
eksekutor -- UC3
eksekutor -- UC4
admin -- UC5
warga -- UC6

UC1 ..> UC_Status : <<include>>
UC2 ..> UC_Status : <<include>>
UC5 ..> UC_Status : <<include>>
UC6 ..> UC_Upvote : <<include>>
UC_Rework ..> UC5 : <<extend>>


@enduml